// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/protobuf/ProtobufEvent.proto

package io.nadron.handlers.netty;

public final class ProtobufEventProtocol {
  private ProtobufEventProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(io.nadron.handlers.netty.ProtobufEventProtocol.credentials);
  }
  public interface MessageOrBuilder extends 
       com.google.protobuf.GeneratedMessageLite.
            ExtendableMessageOrBuilder<Message> {

    // required uint32 event = 1;
    /**
     * <code>required uint32 event = 1;</code>
     *
     * <pre>
     * 事件类型、事件主题
     * </pre>
     */
    boolean hasEvent();
    /**
     * <code>required uint32 event = 1;</code>
     *
     * <pre>
     * 事件类型、事件主题
     * </pre>
     */
    int getEvent();

    // optional string tag = 2 [default = "Proto"];
    /**
     * <code>optional string tag = 2 [default = "Proto"];</code>
     *
     * <pre>
     * 消息类型,5位String
     * </pre>
     */
    boolean hasTag();
    /**
     * <code>optional string tag = 2 [default = "Proto"];</code>
     *
     * <pre>
     * 消息类型,5位String
     * </pre>
     */
    java.lang.String getTag();
    /**
     * <code>optional string tag = 2 [default = "Proto"];</code>
     *
     * <pre>
     * 消息类型,5位String
     * </pre>
     */
    com.google.protobuf.ByteString
        getTagBytes();

    // optional string version = 3 [default = "0.1.4"];
    /**
     * <code>optional string version = 3 [default = "0.1.4"];</code>
     *
     * <pre>
     * 消息版本,5位String
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 3 [default = "0.1.4"];</code>
     *
     * <pre>
     * 消息版本,5位String
     * </pre>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 3 [default = "0.1.4"];</code>
     *
     * <pre>
     * 消息版本,5位String
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    // optional string description = 4;
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 事件描述
     * </pre>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 事件描述
     * </pre>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 事件描述
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // optional string sender = 5;
    /**
     * <code>optional string sender = 5;</code>
     *
     * <pre>
     * 发送者
     * </pre>
     */
    boolean hasSender();
    /**
     * <code>optional string sender = 5;</code>
     *
     * <pre>
     * 发送者
     * </pre>
     */
    java.lang.String getSender();
    /**
     * <code>optional string sender = 5;</code>
     *
     * <pre>
     * 发送者
     * </pre>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    // optional string receiver = 6;
    /**
     * <code>optional string receiver = 6;</code>
     *
     * <pre>
     * 接收者
     * </pre>
     */
    boolean hasReceiver();
    /**
     * <code>optional string receiver = 6;</code>
     *
     * <pre>
     * 接收者
     * </pre>
     */
    java.lang.String getReceiver();
    /**
     * <code>optional string receiver = 6;</code>
     *
     * <pre>
     * 接收者
     * </pre>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    // optional uint64 sequence = 7;
    /**
     * <code>optional uint64 sequence = 7;</code>
     *
     * <pre>
     * 消息序列
     * </pre>
     */
    boolean hasSequence();
    /**
     * <code>optional uint64 sequence = 7;</code>
     *
     * <pre>
     * 消息序列
     * </pre>
     */
    long getSequence();

    // optional uint64 timestamp = 8;
    /**
     * <code>optional uint64 timestamp = 8;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 8;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageLite.ExtendableMessage<
        Message> implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageLite.ExtendableBuilder<io.nadron.handlers.netty.ProtobufEventProtocol.Message, ?> builder) {
      super(builder);

    }
    private Message(boolean noInit) {}

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
//      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              event_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              tag_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              version_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              description_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sender_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              receiver_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              sequence_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 event = 1;
    public static final int EVENT_FIELD_NUMBER = 1;
    private int event_;
    /**
     * <code>required uint32 event = 1;</code>
     *
     * <pre>
     * 事件类型、事件主题
     * </pre>
     */
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 event = 1;</code>
     *
     * <pre>
     * 事件类型、事件主题
     * </pre>
     */
    public int getEvent() {
      return event_;
    }

    // optional string tag = 2 [default = "Proto"];
    public static final int TAG_FIELD_NUMBER = 2;
    private java.lang.Object tag_;
    /**
     * <code>optional string tag = 2 [default = "Proto"];</code>
     *
     * <pre>
     * 消息类型,5位String
     * </pre>
     */
    public boolean hasTag() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string tag = 2 [default = "Proto"];</code>
     *
     * <pre>
     * 消息类型,5位String
     * </pre>
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tag = 2 [default = "Proto"];</code>
     *
     * <pre>
     * 消息类型,5位String
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string version = 3 [default = "0.1.4"];
    public static final int VERSION_FIELD_NUMBER = 3;
    private java.lang.Object version_;
    /**
     * <code>optional string version = 3 [default = "0.1.4"];</code>
     *
     * <pre>
     * 消息版本,5位String
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string version = 3 [default = "0.1.4"];</code>
     *
     * <pre>
     * 消息版本,5位String
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 3 [default = "0.1.4"];</code>
     *
     * <pre>
     * 消息版本,5位String
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string description = 4;
    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 事件描述
     * </pre>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 事件描述
     * </pre>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 事件描述
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sender = 5;
    public static final int SENDER_FIELD_NUMBER = 5;
    private java.lang.Object sender_;
    /**
     * <code>optional string sender = 5;</code>
     *
     * <pre>
     * 发送者
     * </pre>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string sender = 5;</code>
     *
     * <pre>
     * 发送者
     * </pre>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sender = 5;</code>
     *
     * <pre>
     * 发送者
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string receiver = 6;
    public static final int RECEIVER_FIELD_NUMBER = 6;
    private java.lang.Object receiver_;
    /**
     * <code>optional string receiver = 6;</code>
     *
     * <pre>
     * 接收者
     * </pre>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string receiver = 6;</code>
     *
     * <pre>
     * 接收者
     * </pre>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string receiver = 6;</code>
     *
     * <pre>
     * 接收者
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 sequence = 7;
    public static final int SEQUENCE_FIELD_NUMBER = 7;
    private long sequence_;
    /**
     * <code>optional uint64 sequence = 7;</code>
     *
     * <pre>
     * 消息序列
     * </pre>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 sequence = 7;</code>
     *
     * <pre>
     * 消息序列
     * </pre>
     */
    public long getSequence() {
      return sequence_;
    }

    // optional uint64 timestamp = 8;
    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 8;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 timestamp = 8;</code>
     *
     * <pre>
     * 时间戳
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      event_ = 0;
      tag_ = "Proto";
      version_ = "0.1.4";
      description_ = "";
      sender_ = "";
      receiver_ = "";
      sequence_ = 0L;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEvent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessageLite
        .ExtendableMessage<io.nadron.handlers.netty.ProtobufEventProtocol.Message>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, event_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTagBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getVersionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSenderBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getReceiverBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, sequence_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(8, timestamp_);
      }
      extensionWriter.writeUntil(200, output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, event_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTagBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getVersionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSenderBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getReceiverBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, sequence_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, timestamp_);
      }
      size += extensionsSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.nadron.handlers.netty.ProtobufEventProtocol.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.ExtendableBuilder<
          io.nadron.handlers.netty.ProtobufEventProtocol.Message, Builder> implements io.nadron.handlers.netty.ProtobufEventProtocol.MessageOrBuilder {
      // Construct using io.nadron.handlers.netty.ProtobufEventProtocol.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        event_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        tag_ = "Proto";
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = "0.1.4";
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        receiver_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public io.nadron.handlers.netty.ProtobufEventProtocol.Message getDefaultInstanceForType() {
        return io.nadron.handlers.netty.ProtobufEventProtocol.Message.getDefaultInstance();
      }

      public io.nadron.handlers.netty.ProtobufEventProtocol.Message build() {
        io.nadron.handlers.netty.ProtobufEventProtocol.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.nadron.handlers.netty.ProtobufEventProtocol.Message buildPartial() {
        io.nadron.handlers.netty.ProtobufEventProtocol.Message result = new io.nadron.handlers.netty.ProtobufEventProtocol.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.event_ = event_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.receiver_ = receiver_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(io.nadron.handlers.netty.ProtobufEventProtocol.Message other) {
        if (other == io.nadron.handlers.netty.ProtobufEventProtocol.Message.getDefaultInstance()) return this;
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        if (other.hasTag()) {
          bitField0_ |= 0x00000002;
          tag_ = other.tag_;
          
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000004;
          version_ = other.version_;
          
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000008;
          description_ = other.description_;
          
        }
        if (other.hasSender()) {
          bitField0_ |= 0x00000010;
          sender_ = other.sender_;
          
        }
        if (other.hasReceiver()) {
          bitField0_ |= 0x00000020;
          receiver_ = other.receiver_;
          
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeExtensionFields(other);
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEvent()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.nadron.handlers.netty.ProtobufEventProtocol.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.nadron.handlers.netty.ProtobufEventProtocol.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 event = 1;
      private int event_ ;
      /**
       * <code>required uint32 event = 1;</code>
       *
       * <pre>
       * 事件类型、事件主题
       * </pre>
       */
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 event = 1;</code>
       *
       * <pre>
       * 事件类型、事件主题
       * </pre>
       */
      public int getEvent() {
        return event_;
      }
      /**
       * <code>required uint32 event = 1;</code>
       *
       * <pre>
       * 事件类型、事件主题
       * </pre>
       */
      public Builder setEvent(int value) {
        bitField0_ |= 0x00000001;
        event_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 event = 1;</code>
       *
       * <pre>
       * 事件类型、事件主题
       * </pre>
       */
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        event_ = 0;
        
        return this;
      }

      // optional string tag = 2 [default = "Proto"];
      private java.lang.Object tag_ = "Proto";
      /**
       * <code>optional string tag = 2 [default = "Proto"];</code>
       *
       * <pre>
       * 消息类型,5位String
       * </pre>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string tag = 2 [default = "Proto"];</code>
       *
       * <pre>
       * 消息类型,5位String
       * </pre>
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tag = 2 [default = "Proto"];</code>
       *
       * <pre>
       * 消息类型,5位String
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tag = 2 [default = "Proto"];</code>
       *
       * <pre>
       * 消息类型,5位String
       * </pre>
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tag_ = value;
        
        return this;
      }
      /**
       * <code>optional string tag = 2 [default = "Proto"];</code>
       *
       * <pre>
       * 消息类型,5位String
       * </pre>
       */
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tag_ = getDefaultInstance().getTag();
        
        return this;
      }
      /**
       * <code>optional string tag = 2 [default = "Proto"];</code>
       *
       * <pre>
       * 消息类型,5位String
       * </pre>
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tag_ = value;
        
        return this;
      }

      // optional string version = 3 [default = "0.1.4"];
      private java.lang.Object version_ = "0.1.4";
      /**
       * <code>optional string version = 3 [default = "0.1.4"];</code>
       *
       * <pre>
       * 消息版本,5位String
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string version = 3 [default = "0.1.4"];</code>
       *
       * <pre>
       * 消息版本,5位String
       * </pre>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 3 [default = "0.1.4"];</code>
       *
       * <pre>
       * 消息版本,5位String
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 3 [default = "0.1.4"];</code>
       *
       * <pre>
       * 消息版本,5位String
       * </pre>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        
        return this;
      }
      /**
       * <code>optional string version = 3 [default = "0.1.4"];</code>
       *
       * <pre>
       * 消息版本,5位String
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = getDefaultInstance().getVersion();
        
        return this;
      }
      /**
       * <code>optional string version = 3 [default = "0.1.4"];</code>
       *
       * <pre>
       * 消息版本,5位String
       * </pre>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        version_ = value;
        
        return this;
      }

      // optional string description = 4;
      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 事件描述
       * </pre>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 事件描述
       * </pre>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 事件描述
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 事件描述
       * </pre>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 事件描述
       * </pre>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = getDefaultInstance().getDescription();
        
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 事件描述
       * </pre>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        
        return this;
      }

      // optional string sender = 5;
      private java.lang.Object sender_ = "";
      /**
       * <code>optional string sender = 5;</code>
       *
       * <pre>
       * 发送者
       * </pre>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sender = 5;</code>
       *
       * <pre>
       * 发送者
       * </pre>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sender = 5;</code>
       *
       * <pre>
       * 发送者
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sender = 5;</code>
       *
       * <pre>
       * 发送者
       * </pre>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sender_ = value;
        
        return this;
      }
      /**
       * <code>optional string sender = 5;</code>
       *
       * <pre>
       * 发送者
       * </pre>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sender_ = getDefaultInstance().getSender();
        
        return this;
      }
      /**
       * <code>optional string sender = 5;</code>
       *
       * <pre>
       * 发送者
       * </pre>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sender_ = value;
        
        return this;
      }

      // optional string receiver = 6;
      private java.lang.Object receiver_ = "";
      /**
       * <code>optional string receiver = 6;</code>
       *
       * <pre>
       * 接收者
       * </pre>
       */
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string receiver = 6;</code>
       *
       * <pre>
       * 接收者
       * </pre>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiver = 6;</code>
       *
       * <pre>
       * 接收者
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiver = 6;</code>
       *
       * <pre>
       * 接收者
       * </pre>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        receiver_ = value;
        
        return this;
      }
      /**
       * <code>optional string receiver = 6;</code>
       *
       * <pre>
       * 接收者
       * </pre>
       */
      public Builder clearReceiver() {
        bitField0_ = (bitField0_ & ~0x00000020);
        receiver_ = getDefaultInstance().getReceiver();
        
        return this;
      }
      /**
       * <code>optional string receiver = 6;</code>
       *
       * <pre>
       * 接收者
       * </pre>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        receiver_ = value;
        
        return this;
      }

      // optional uint64 sequence = 7;
      private long sequence_ ;
      /**
       * <code>optional uint64 sequence = 7;</code>
       *
       * <pre>
       * 消息序列
       * </pre>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 sequence = 7;</code>
       *
       * <pre>
       * 消息序列
       * </pre>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional uint64 sequence = 7;</code>
       *
       * <pre>
       * 消息序列
       * </pre>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000040;
        sequence_ = value;
        
        return this;
      }
      /**
       * <code>optional uint64 sequence = 7;</code>
       *
       * <pre>
       * 消息序列
       * </pre>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sequence_ = 0L;
        
        return this;
      }

      // optional uint64 timestamp = 8;
      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 8;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint64 timestamp = 8;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 8;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000080;
        timestamp_ = value;
        
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 8;</code>
       *
       * <pre>
       * 时间戳
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        timestamp_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.Message)
  }

  public interface CredentialsOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string username = 1;
    /**
     * <code>optional string username = 1;</code>
     *
     * <pre>
     * 登录名称
     * </pre>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 1;</code>
     *
     * <pre>
     * 登录名称
     * </pre>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     *
     * <pre>
     * 登录名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // optional string password = 2;
    /**
     * <code>optional string password = 2;</code>
     *
     * <pre>
     * 登陆密码
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2;</code>
     *
     * <pre>
     * 登陆密码
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     *
     * <pre>
     * 登陆密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional string sessionKey = 3;
    /**
     * <code>optional string sessionKey = 3;</code>
     *
     * <pre>
     * 重新连接会话票据
     * </pre>
     */
    boolean hasSessionKey();
    /**
     * <code>optional string sessionKey = 3;</code>
     *
     * <pre>
     * 重新连接会话票据
     * </pre>
     */
    java.lang.String getSessionKey();
    /**
     * <code>optional string sessionKey = 3;</code>
     *
     * <pre>
     * 重新连接会话票据
     * </pre>
     */
    com.google.protobuf.ByteString
        getSessionKeyBytes();

    // optional string areaId = 4;
    /**
     * <code>optional string areaId = 4;</code>
     *
     * <pre>
     * 区域ID
     * </pre>
     */
    boolean hasAreaId();
    /**
     * <code>optional string areaId = 4;</code>
     *
     * <pre>
     * 区域ID
     * </pre>
     */
    java.lang.String getAreaId();
    /**
     * <code>optional string areaId = 4;</code>
     *
     * <pre>
     * 区域ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getAreaIdBytes();

    // optional string localUDPAddress = 6;
    /**
     * <code>optional string localUDPAddress = 6;</code>
     *
     * <pre>
     * UDP
     * </pre>
     */
    boolean hasLocalUDPAddress();
    /**
     * <code>optional string localUDPAddress = 6;</code>
     *
     * <pre>
     * UDP
     * </pre>
     */
    java.lang.String getLocalUDPAddress();
    /**
     * <code>optional string localUDPAddress = 6;</code>
     *
     * <pre>
     * UDP
     * </pre>
     */
    com.google.protobuf.ByteString
        getLocalUDPAddressBytes();
  }
  /**
   * Protobuf type {@code com.Credentials}
   */
  public static final class Credentials extends
      com.google.protobuf.GeneratedMessageLite
      implements CredentialsOrBuilder {
    // Use Credentials.newBuilder() to construct.
    private Credentials(@SuppressWarnings("rawtypes") com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Credentials(boolean noInit) {}

    private static final Credentials defaultInstance;
    public static Credentials getDefaultInstance() {
      return defaultInstance;
    }

    public Credentials getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Credentials(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
//      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessionKey_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              areaId_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              localUDPAddress_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Credentials> PARSER =
        new com.google.protobuf.AbstractParser<Credentials>() {
      public Credentials parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Credentials(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Credentials> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 1;</code>
     *
     * <pre>
     * 登录名称
     * </pre>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string username = 1;</code>
     *
     * <pre>
     * 登录名称
     * </pre>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     *
     * <pre>
     * 登录名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     *
     * <pre>
     * 登陆密码
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2;</code>
     *
     * <pre>
     * 登陆密码
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     *
     * <pre>
     * 登陆密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sessionKey = 3;
    public static final int SESSIONKEY_FIELD_NUMBER = 3;
    private java.lang.Object sessionKey_;
    /**
     * <code>optional string sessionKey = 3;</code>
     *
     * <pre>
     * 重新连接会话票据
     * </pre>
     */
    public boolean hasSessionKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sessionKey = 3;</code>
     *
     * <pre>
     * 重新连接会话票据
     * </pre>
     */
    public java.lang.String getSessionKey() {
      java.lang.Object ref = sessionKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionKey = 3;</code>
     *
     * <pre>
     * 重新连接会话票据
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSessionKeyBytes() {
      java.lang.Object ref = sessionKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string areaId = 4;
    public static final int AREAID_FIELD_NUMBER = 4;
    private java.lang.Object areaId_;
    /**
     * <code>optional string areaId = 4;</code>
     *
     * <pre>
     * 区域ID
     * </pre>
     */
    public boolean hasAreaId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string areaId = 4;</code>
     *
     * <pre>
     * 区域ID
     * </pre>
     */
    public java.lang.String getAreaId() {
      java.lang.Object ref = areaId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          areaId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string areaId = 4;</code>
     *
     * <pre>
     * 区域ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAreaIdBytes() {
      java.lang.Object ref = areaId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string localUDPAddress = 6;
    public static final int LOCALUDPADDRESS_FIELD_NUMBER = 6;
    private java.lang.Object localUDPAddress_;
    /**
     * <code>optional string localUDPAddress = 6;</code>
     *
     * <pre>
     * UDP
     * </pre>
     */
    public boolean hasLocalUDPAddress() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string localUDPAddress = 6;</code>
     *
     * <pre>
     * UDP
     * </pre>
     */
    public java.lang.String getLocalUDPAddress() {
      java.lang.Object ref = localUDPAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localUDPAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string localUDPAddress = 6;</code>
     *
     * <pre>
     * UDP
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLocalUDPAddressBytes() {
      java.lang.Object ref = localUDPAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localUDPAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      username_ = "";
      password_ = "";
      sessionKey_ = "";
      areaId_ = "";
      localUDPAddress_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAreaIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getLocalUDPAddressBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAreaIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getLocalUDPAddressBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.nadron.handlers.netty.ProtobufEventProtocol.Credentials prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.Credentials}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.nadron.handlers.netty.ProtobufEventProtocol.Credentials, Builder>
        implements io.nadron.handlers.netty.ProtobufEventProtocol.CredentialsOrBuilder {
      // Construct using io.nadron.handlers.netty.ProtobufEventProtocol.Credentials.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        areaId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        localUDPAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public io.nadron.handlers.netty.ProtobufEventProtocol.Credentials getDefaultInstanceForType() {
        return io.nadron.handlers.netty.ProtobufEventProtocol.Credentials.getDefaultInstance();
      }

      public io.nadron.handlers.netty.ProtobufEventProtocol.Credentials build() {
        io.nadron.handlers.netty.ProtobufEventProtocol.Credentials result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.nadron.handlers.netty.ProtobufEventProtocol.Credentials buildPartial() {
        io.nadron.handlers.netty.ProtobufEventProtocol.Credentials result = new io.nadron.handlers.netty.ProtobufEventProtocol.Credentials(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionKey_ = sessionKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.areaId_ = areaId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.localUDPAddress_ = localUDPAddress_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(io.nadron.handlers.netty.ProtobufEventProtocol.Credentials other) {
        if (other == io.nadron.handlers.netty.ProtobufEventProtocol.Credentials.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          
        }
        if (other.hasSessionKey()) {
          bitField0_ |= 0x00000004;
          sessionKey_ = other.sessionKey_;
          
        }
        if (other.hasAreaId()) {
          bitField0_ |= 0x00000008;
          areaId_ = other.areaId_;
          
        }
        if (other.hasLocalUDPAddress()) {
          bitField0_ |= 0x00000010;
          localUDPAddress_ = other.localUDPAddress_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.nadron.handlers.netty.ProtobufEventProtocol.Credentials parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.nadron.handlers.netty.ProtobufEventProtocol.Credentials) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string username = 1;
      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       *
       * <pre>
       * 登录名称
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string username = 1;</code>
       *
       * <pre>
       * 登录名称
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       *
       * <pre>
       * 登录名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       *
       * <pre>
       * 登录名称
       * </pre>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       *
       * <pre>
       * 登录名称
       * </pre>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       *
       * <pre>
       * 登录名称
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        
        return this;
      }

      // optional string password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       *
       * <pre>
       * 登陆密码
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2;</code>
       *
       * <pre>
       * 登陆密码
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       *
       * <pre>
       * 登陆密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       *
       * <pre>
       * 登陆密码
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       *
       * <pre>
       * 登陆密码
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       *
       * <pre>
       * 登陆密码
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }

      // optional string sessionKey = 3;
      private java.lang.Object sessionKey_ = "";
      /**
       * <code>optional string sessionKey = 3;</code>
       *
       * <pre>
       * 重新连接会话票据
       * </pre>
       */
      public boolean hasSessionKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       *
       * <pre>
       * 重新连接会话票据
       * </pre>
       */
      public java.lang.String getSessionKey() {
        java.lang.Object ref = sessionKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       *
       * <pre>
       * 重新连接会话票据
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSessionKeyBytes() {
        java.lang.Object ref = sessionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       *
       * <pre>
       * 重新连接会话票据
       * </pre>
       */
      public Builder setSessionKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionKey_ = value;
        
        return this;
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       *
       * <pre>
       * 重新连接会话票据
       * </pre>
       */
      public Builder clearSessionKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionKey_ = getDefaultInstance().getSessionKey();
        
        return this;
      }
      /**
       * <code>optional string sessionKey = 3;</code>
       *
       * <pre>
       * 重新连接会话票据
       * </pre>
       */
      public Builder setSessionKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionKey_ = value;
        
        return this;
      }

      // optional string areaId = 4;
      private java.lang.Object areaId_ = "";
      /**
       * <code>optional string areaId = 4;</code>
       *
       * <pre>
       * 区域ID
       * </pre>
       */
      public boolean hasAreaId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string areaId = 4;</code>
       *
       * <pre>
       * 区域ID
       * </pre>
       */
      public java.lang.String getAreaId() {
        java.lang.Object ref = areaId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          areaId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string areaId = 4;</code>
       *
       * <pre>
       * 区域ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAreaIdBytes() {
        java.lang.Object ref = areaId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          areaId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string areaId = 4;</code>
       *
       * <pre>
       * 区域ID
       * </pre>
       */
      public Builder setAreaId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        areaId_ = value;
        
        return this;
      }
      /**
       * <code>optional string areaId = 4;</code>
       *
       * <pre>
       * 区域ID
       * </pre>
       */
      public Builder clearAreaId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        areaId_ = getDefaultInstance().getAreaId();
        
        return this;
      }
      /**
       * <code>optional string areaId = 4;</code>
       *
       * <pre>
       * 区域ID
       * </pre>
       */
      public Builder setAreaIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        areaId_ = value;
        
        return this;
      }

      // optional string localUDPAddress = 6;
      private java.lang.Object localUDPAddress_ = "";
      /**
       * <code>optional string localUDPAddress = 6;</code>
       *
       * <pre>
       * UDP
       * </pre>
       */
      public boolean hasLocalUDPAddress() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string localUDPAddress = 6;</code>
       *
       * <pre>
       * UDP
       * </pre>
       */
      public java.lang.String getLocalUDPAddress() {
        java.lang.Object ref = localUDPAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localUDPAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string localUDPAddress = 6;</code>
       *
       * <pre>
       * UDP
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLocalUDPAddressBytes() {
        java.lang.Object ref = localUDPAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localUDPAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string localUDPAddress = 6;</code>
       *
       * <pre>
       * UDP
       * </pre>
       */
      public Builder setLocalUDPAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        localUDPAddress_ = value;
        
        return this;
      }
      /**
       * <code>optional string localUDPAddress = 6;</code>
       *
       * <pre>
       * UDP
       * </pre>
       */
      public Builder clearLocalUDPAddress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        localUDPAddress_ = getDefaultInstance().getLocalUDPAddress();
        
        return this;
      }
      /**
       * <code>optional string localUDPAddress = 6;</code>
       *
       * <pre>
       * UDP
       * </pre>
       */
      public Builder setLocalUDPAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        localUDPAddress_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.Credentials)
    }

    static {
      defaultInstance = new Credentials(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.Credentials)
  }

  public static final int CREDENTIALS_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.Message { ... }</code>
   *
   * <pre>
   * 事件类型、事件主题
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      io.nadron.handlers.netty.ProtobufEventProtocol.Message,
      io.nadron.handlers.netty.ProtobufEventProtocol.Credentials> credentials = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        io.nadron.handlers.netty.ProtobufEventProtocol.Message.getDefaultInstance(),
        io.nadron.handlers.netty.ProtobufEventProtocol.Credentials.getDefaultInstance(),
        io.nadron.handlers.netty.ProtobufEventProtocol.Credentials.getDefaultInstance(),
        null,
        100,
        com.google.protobuf.WireFormat.FieldType.MESSAGE);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
