package com.badugi.game.logic.model.entity;

// Generated 2015-12-2 10:38:48 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RacingPool generated by hbm2java
 */
@Entity
@Table(name = "racing_pool")
public class RacingPool extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3488513431963399984L;
	private String rid;
	private Long UId;
	private Integer disRobot;
	//wtu.edit 2015-12-15 增加玩家庄和玩家闲输赢
	private Double dwinchips;//玩家庄
	private Double fwinchips;//玩家闲
	//------------------
	private Double chips;
	private Double oldPoolChips;
	private Double dpump;
	private Double fpump;
	private Double poolPump;
	private Date createTime;

	public RacingPool() {
	}

	public RacingPool(String rid) {
		this.rid = rid;
	}

	public RacingPool(String rid, Long UId, Integer disRobot, Double chips,
			Double oldPoolChips, Double dpump, Double fpump, Double poolPump,
			Date createTime) {
		this.rid = rid;
		this.UId = UId;
		this.disRobot = disRobot;
		this.chips = chips;
		this.oldPoolChips = oldPoolChips;
		this.dpump = dpump;
		this.fpump = fpump;
		this.poolPump = poolPump;
		this.createTime = createTime;
	}

	@Id
	@Column(name = "rid", unique = true, nullable = false)
	public String getRid() {
		return this.rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

	@Column(name = "u_id")
	public Long getUId() {
		return this.UId;
	}

	public void setUId(Long UId) {
		this.UId = UId;
	}

	@Column(name = "dIsRobot")
	public Integer getDisRobot() {
		return this.disRobot;
	}

	public void setDisRobot(Integer disRobot) {
		this.disRobot = disRobot;
	}
	
	/**
	 * @return dwinchips
	 */
	@Column(name = "dwinchips", precision = 22, scale = 0)
	public Double getDwinchips() {
		return dwinchips;
	}

	/**
	 * @param dwinchips 要设置的 dwinchips
	 */
	public void setDwinchips(Double dwinchips) {
		this.dwinchips = dwinchips;
	}

	/**
	 * @return fwinchips
	 */
	@Column(name = "fwinchips", precision = 22, scale = 0)
	public Double getFwinchips() {
		return fwinchips;
	}

	/**
	 * @param fwinchips 要设置的 fwinchips
	 */
	public void setFwinchips(Double fwinchips) {
		this.fwinchips = fwinchips;
	}

	@Column(name = "chips", precision = 22, scale = 0)
	public Double getChips() {
		return this.chips;
	}

	public void setChips(Double chips) {
		this.chips = chips;
	}

	@Column(name = "old_pool_chips", precision = 22, scale = 0)
	public Double getOldPoolChips() {
		return this.oldPoolChips;
	}

	public void setOldPoolChips(Double oldPoolChips) {
		this.oldPoolChips = oldPoolChips;
	}

	@Column(name = "dpump", precision = 22, scale = 0)
	public Double getDpump() {
		return this.dpump;
	}

	public void setDpump(Double dpump) {
		this.dpump = dpump;
	}

	@Column(name = "fpump", precision = 22, scale = 0)
	public Double getFpump() {
		return this.fpump;
	}

	public void setFpump(Double fpump) {
		this.fpump = fpump;
	}

	@Column(name = "pool_pump", precision = 22, scale = 0)
	public Double getPoolPump() {
		return this.poolPump;
	}

	public void setPoolPump(Double poolPump) {
		this.poolPump = poolPump;
	}

	
	@Column(name = "create_time")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/* （非 Javadoc）
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "RacingPool [rid=" + rid + ", UId=" + UId + ", disRobot="
				+ disRobot + ", dwinchips=" + dwinchips + ", fwinchips="
				+ fwinchips + ", chips=" + chips + ", oldPoolChips="
				+ oldPoolChips + ", dpump=" + dpump + ", fpump=" + fpump
				+ ", poolPump=" + poolPump + ", createTime=" + createTime + "]";
	}

	

	
	
}
